export { default as About } from './lists/about';
export { default as BigPicture } from './lists/bigPicture';
export { default as Event } from './lists/event';
export { default as Filter } from './lists/filter';
export { default as Home } from './lists/home';
export { default as HomeSlide } from './lists/homeSlide';
export { default as MediaItem } from './lists/media';
export { default as NewsItem } from './lists/newsItem';
export { default as Person } from './lists/person';
export { default as Studio } from './lists/studio';
export { default as User } from './lists/user';
export { default as DataTemp } from './lists/dataTemp'
