version: '3'

services:
  traefik:
    image: traefik:v2.9
    ports:
      - 80:80
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./proxy/traefik.dev.yml:/traefik.yml
    logging:
      driver: none
    labels:
      - "traefik.http.routers.dashboard.rule=(PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"

  # cms-landing:
  #   image: ghcr.io/patrickdappollonio/docker-http-server:v2
  #   command: --path /html --title "ELab CMS Directory"
  #   volumes:
  #     - ./_site/index.html:/html/index.html
  #   labels:
  #     traefik.http.routers.cms-landing.rule: PathPrefix(`/`)
  #     traefik.http.routers.cms-landing.entrypoints: web

  # devapi:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: api
  #   env_file:
  #     - ./apps/api/.env
  #   environment:
  #     - PORT=8000
  #     - ENV=development
  #   labels:
  #     - "traefik.http.routers.devapi.rule=PathPrefix(`/devapi`)"
  #     - "traefik.http.routers.devapi.entrypoints=web"
  #     - "traefik.http.routers.devapi.service=api-el-next"
  #     - "traefik.http.services.api-el-next.loadbalancer.server.port=8000"
  #     - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/devapi"
  #     - "traefik.http.routers.devapi.middlewares=api-stripprefix"

  cms-elab:
    hostname: cms-elab
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
      target: cms-runner
      args:
        - APP_NAME=elab
        - PORT=3000
    env_file:
      - ./apps/cms/.env
    environment:
      - PORT=3000
    labels:
      - "traefik.http.routers.cms-elab.rule=PathPrefix(`/elab`)"
      - "traefik.http.routers.cms-elab.entrypoints=web"
      - "traefik.http.routers.cms-elab.service=cms-elab-transform-narratives"

  # cms-sjm:
  #   hostname: cms-sjm
  #   ports:
  #     - "3001:3001"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: cms-runner
  #     args:
  #       - APP_NAME=sjm
  #       - PORT=3001
  #   env_file:
  #     - ./apps/cms/.env
  #   environment:
  #     - PORT=3001
  #   labels:
  #     - "traefik.http.routers.cms-sjm.rule=PathPrefix(`/sjm`)"
  #     - "traefik.http.routers.cms-sjm.entrypoints=web"
  #     - "traefik.http.routers.cms-sjm.service=cms-sjm-transform-narratives"

  # qa-sjm:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: qa-image
  #     args:
  #       APP: sjm
  #       PORT: 8082
  #   environment:
  #     WAIT_HOSTS: cms-sjm:3001
  #   labels:
  #     - "traefik.http.routers.qa-sjm.entrypoints=web"
  #     - "traefik.http.routers.qa-sjm.service=qa-sjm-transform-narratives"
  #     - "traefik.http.services.qa-sjm-transform-narratives.loadbalancer.server.port=8082"

  # qa-elab:
  #     build:
  #       context: .
  #       dockerfile: Dockerfile
  #       target: qa-image
  #       args:
  #         APP: elab
  #         PORT: 8083
  #         CMS_ENDPOINT: cms-elab:3002
  #     restart: on-failure
  #     labels:
  #       - 'traefik.http.routers.qa-elab-http.entrypoints=web'
  #       - 'traefik.http.routers.qa-elab.service=qa-elab-el-next'
  #       - 'traefik.http.services.qa-elab-el-next.loadbalancer.server.port=8083'

  # traefik-forward-auth:
  #   image: thomseddon/traefik-forward-auth:latest
  #   env_file: ./apps/cms/.auth.env
  #   labels:
  #     - 'traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181'
  #     - 'traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User'
  #     - 'traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181'
  #     - 'traefik.http.routers.traefik-forward-auth.rule=PathPrefix(`/_oauth`)'
      
  # error-pages:
  #   image: ghcr.io/patrickdappollonio/docker-http-server:v2
  #   command: --path /html --port 5001
  #   volumes:
  #     - ./_site:/html
  #   labels:
  #     traefik.enable: 'true'
  #     traefik.http.services.error-pages-el-next.loadbalancer.server.port: 5001
  #     traefik.http.routers.error-pages.entrypoints: websecure
  #     traefik.http.routers.error-pages.rule: HostRegexp(`error-pages.cms.elab.emerson.edu`)
  #     traefik.http.routers.error-pages.priority: 1
  #     traefik.http.middlewares.error-pages.errors.status: 400-599
  #     traefik.http.middlewares.error-pages.errors.service: error-pages-el-next
  #     traefik.http.middlewares.error-pages.errors.query: /error.html
