version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./proxy/traefik.yml:/traefik.yml
      - ./proxy/certs.yml:/certs.yml
      - /etc/ssl/certs:/certs
    networks:
      - web
    labels:
      - "traefik.http.routers.dashboard.rule=(PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
    restart: always

  cms-tngvi:
    image: el-next
    env_file:
      - ./apps/cms/.env
    environment:
      - APP_NAME=tngvi
      - PORT=3000
    networks:
      - web
    ports:
      - 3000:3000
    labels:
      - "traefik.http.routers.cms-tngvi.rule=PathPrefix(`/tngvi`)"
      - "traefik.http.routers.cms-tngvi.tls=true"
      - "traefik.http.routers.cms-tngvi.entrypoints=websecure"
      - "traefik.http.routers.cms-tngvi.service=cms-tngvi-el-next"

  cms-sjm:
    image: el-next
    env_file:
      - ./apps/cms/.env
    environment:
      - APP_NAME=sjm
      - PORT=3001
    networks:
      - web
    ports:
      - 3001:3001
    labels:
      - "traefik.http.routers.cms-sjm.rule=PathPrefix(`/sjm`)"
      - "traefik.http.routers.cms-sjm.tls=true"
      - "traefik.http.routers.cms-sjm.entrypoints=websecure"
      - "traefik.http.routers.cms-sjm.service=cms-sjm-el-next"
      - "traefik.http.services.cms-sjm-el-next.loadbalancer.server.port=3001"

networks:
  web:
    driver: bridge
    ipam:
      driver: default
