## Static configuration
log:
  # level: WARN
  # level: INFO
  level: DEBUG
accessLog: {}
entryPoints:
  web:
   address: ":80"
   http:
     redirections:
       entryPoint:
         to: websecure
         scheme: https
         permanent: true
  websecure:
   address: ":443"
api:
  dashboard: true
  insecure: true
providers:
  docker: 
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    watch: false
    # exposedByDefault: false
    # swarmMode:
  file:
    filename: certs.yml
   
# certificatesResolvers:
#   cmsCertResolver:
#     acme:
#       email: john_richardson@emerson.edu
#       storage: acme.json
#       httpChallenge:
#         # used during the challenge
#         entryPoint: web