## Static configuration
# log:
  # level: WARN
  # level: INFO
  # level: DEBUG
# accessLog: {}
entryPoints:
  web:
   address: ":80"
   http:
     redirections:
       entryPoint:
         to: websecure
         scheme: https
         permanent: true
  websecure:
   address: ":443"
# api:
#   dashboard: true
#   insecure: true
providers:
  docker: 
    watch: false
  file:
    filename: certs.yml
certificatesResolvers:
  letsencrypt:
    # Enable ACME (Let's Encrypt): automatic SSL.
    acme:
      email: "engagementlab@emerson.edu"
      storage: "acme.json"
      tlsChallenge: