name: build
on: 
  repository_dispatch:
    types: deploy-prod
  push:
    branches: [main]
  pull_request:
    branches: [production]
env:
  CI: true
  DB_URI: ${{ secrets.DB_URI }}
  NODE_ENV: production
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
jobs:
  build-tests:
    name: "Make build, run accessibility checks, deploy to production as needed"
    # Do not run on automated commits (interpretation of TravisCI feature)
    if: "!contains(github.event.head_commit.message, 'skip ci') &&  github.actor != 'dependabot[bot]'"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.1]
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout code on HEAD
        uses: actions/checkout@v2
        if: ${{ github.event_name != 'pull_request' }}

      # Do this only for PR to production, since we need to work on main during later commit, and PR's work off of merge ref
      - name: Checkout code of PR HEAD
        uses: actions/checkout@v2
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Setup node.js ${{ matrix.node-version }}
      
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install global packages
        run : npm install -g pa11y-ci http-server @lhci/cli@0.6.x yarn pm2

      - name: Run CMS
        working-directory: ./apps/cms  
        env:
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
          DB_URI: ${{ secrets.DB_URI}}
        run: |
          yarn add typescript @types/node
          yarn
          yarn build
          pm2 start yarn --name "el-cms-new" -- dev --port 8000 --app tngvi

      - name: Make production build
        working-directory: ./apps/tngvi  
        env:
          APOLLO_CLIENT_GRAPHQL_URI: ${{ secrets.APOLLO_CLIENT_GRAPHQL_URI}}
        run: |
          yarn add typescript @types/node
          yarn
          yarn build

      - name: Serve build 
        working-directory: ./apps/tngvi  
        run: http-server out/ > http.log 2>&1 &

      - name: Output all build paths to .pa11yci config and run pa11y
        working-directory: ./apps/tngvi  
        run: |
          node outputRoutes.mjs
          pa11y-ci

      # Deploy static build to Azure storage if succeeded
      - name: Deploy static build
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'repository_dispatch' }}
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GHA_RUNNUM: ${{ github.run_number }}

        # Install azure-cli, run Bash scripts
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          chmod 777 ./scripts/upload.sh && ./scripts/upload.sh
          chmod 777 ./scripts/commit.sh && ./scripts/commit.sh

      - name: Send Slack message on success
        id: slack
        if: ${{ (github.event_name == 'pull_request' || github.event_name == 'repository_dispatch') && success() }}
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # Build succeeded
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":white_check_mark: The latest build of TNGVI has successfully been published to <https://transformnarratives.org/|production>. _(Build #${{ github.run_number }})_"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send Slack message on failure
        id: slack-failure
        if: ${{ (github.event_name == 'pull_request' || github.event_name == 'repository_dispatch') && failure() }}
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # Build failed
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":x: The latest build of TNGVI just failed. _(Build #${{ github.run_number }})_"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "<@U044WFR24> please look at the <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|build logs>."
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK