name: "Checkout latest HEAD commit, make build for all apps"
on: 
  pull_request:
    branches: [production]
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
env:
  NODE_ENV: production
jobs:
  build-setup:
    # Do not run on automated commits (interpretation of TravisCI feature)
    if: "!contains(github.event.head_commit.message, 'skip ci') &&  github.actor != 'dependabot[bot]'"
    name: Setup build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout code on HEAD
        uses: actions/checkout@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          ref: ${{ inputs.branch }}

      # Do this only for PR to production, since we need to work on main during later commit, and PR's work off of merge ref
      - name: Checkout code of PR HEAD
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format('artifact-repo-{0}', github.run_id) }}
          retention-days: 1
          path: ./